### ISSUE TITLE
Unable to access user PATH

### ISSUE THREAD

**Issue by FilBot3** [flathub/org.vim.Vim#113]
When starting vim at the command line, I start vim using this wrapper script 

```bash
#!/usr/bin/env bashh
# Location: ${HOME}/.local/bin/vim

/usr/bin/flatpak run org.vim.Vim $@
```

I am using the latest as of 2020-09-29 of coc.nvim and I have `nvm` managing NodeJS for me which I can execute in a shell. 

However, when started using the Flatpak version of Vim, it cannot find the `node` command because the `${PATH}` isn't there. 

Is this something that I should use `flatpak-spawn --host node` to solve?

**Comment by wjt** [comment]
Yes, if Node is installed to `/usr` on the host, it's not visible inside the Flatpak. This is by design of Flatpak  You should be able to use:

```
flatpak-spawn --host node ...
```

from within the sandbox.
