### ISSUE TITLE
Feature request: Change manifest file to org.freedesktop.Platform as runtime

### ISSUE THREAD

**Issue by igor2x** [flathub/org.vim.Vim#157]
I have checked flatpak runtimes with:  `flatpak list --runtime` on my computer and I see "org.freedesktop.Sdk" is also returned (beside other expected runtimes). Then I have checked every flatpak on my computer and for Vim flatpak:

`flatpak info org.vim.Vim`

and the following is displayed (I have removed non-essential rows):
>  ID: org.vim.Vim
>  Runtime: org.freedesktop.Sdk/x86_64/22.08
>  Sdk: org.freedesktop.Sdk/x86_64/22.08

See both _Runtime_ and _Sdk_ are having the same _org.freedesktop.Sdk_. This is not the best, because:
- org.freedesktop.Sdk should be used only for BUILDING flatpak
- org.freedesktop.Platform should be used for end users to RUN flatpak

Because of "double" _org.freedesktop.Sdk_ settings in vim's manifest file, when "vim" flatpak is installed on end-user computers, also _org.freedesktop.Sdk_ flatpak is installed as dependency. Now when users install multiple flatpaks, then _org.freedesktop.Platform_ flatpak is **shared** between many flatpaks. Vim using org.freedesktop.Sdk unnecessary bloats end-user disk and RAM, because of not sharing runtime with other flatpaks.

Can you please in manifest file `org.vim.Vim.json` replace:
`"runtime": "org.freedesktop.Sdk",`
with
`"runtime": "org.freedesktop.Platform",`
and rebuild flatpak.

By the way, if you are already changing manifest file, can you also at the same time update Vim to the latest minor version.

**Comment by wjt** [comment]
#85 has the rationale for using the SDK as the runtime
